spring.application.name=customer-service

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_JDBC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

